### PR TITLE
Moving Coffee to ES6 + newest LESS version

### PR DESCRIPTION
**Pull request by sdomagala**

### CODE REVIEW

**Comment by sdomagala** [comment]
Hey @docpad/core-team , this pull request is hanging for a while now.
We are using this fork (successfully) for couple months now with ES6.
Test is failing because of some changes in logging in the DocPad (you can see it is failing on destroy step).
Some background:

```
    DocPad.prototype.log = function() {
      var args, logger;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      logger = this.getLogger() || console;
      logger.log.apply(logger, args);
      return this;
    };
```
This line - `logger.log.apply(logger, args);` causes failures in caterpillar but it has nothing to do with this plugin implementation.

Please take a look and if you have no objections please release it to npm (I don't have rights to do so). 
There is a breaking change though (version of less) so I believe it should be v3.0

**Comment by balupton** [comment]
Hold out for now. Sorry it has been nearly a year on this. My financial situation hasn't improved at all since 2014 - but working on it.

Once bevry/sponsored is done, then I will get to work on updating docpad deps, then converting one plugin to the ESNext workflow that can be the base for the rest. After that, I'll focus on a closed-souce products until open-source can become profitable (or rather, not be a net loss) for me.

**Comment by sdomagala** [comment]
This plugin is a must for us so maybe you could provide me with npm permissions so I can carry on with writing plugins or maybe (dont think that's a good idea) I can release them to npm with different name.
I simply cant wait for docpad to become profitable to get those plugins released. We are using forked github repo in our project but we lose many advantages from npm

**Comment by Zearin** [comment]
> This plugin is a must for us so maybe you could provide me with npm permissions so I can carry on with writing plugins or maybe (dont think that's a good idea) I can release them to npm with different name.
> I simply cant wait for docpad to become profitable to get those plugins released. We are using forked github repo in our project but we lose many advantages from npm

I love DocPad’s ambition and goals, and for years I fought to use it and contributed when I could.  But for 100% of those several years, it has been riddled with problems, implemented with a confusing god class, and incredibly slow to fix these shortcomings.  After using it for so long, and giving to it when I was able, it’s not really any closer to the tool that I wanted it to be.  The entire time, I felt like DocPad was “just around the corner” from becoming that tool, but it never happened.

I wish DocPad the best, and I hope it is able to regain traction and fulfill the promise of its destiny.  But until there are signs of that happening, then maybe the best solution for you is to find an alternative to DocPad.  I personally love [Metalsmith](http://metalsmith.io).  DocPad’s own @RobLoach has made some contributions to the project (especially in terms of JSTransformer plugins).  It’s a much more lightweight tool (and performs *very* fast!), incredibly flexible, and has plugins to replicate all the functionality that I loved about DocPad.

It makes me sad to write this, but I don’t want others to torture themselves hoping for a better future that may or may not come.  There are other tools that can do the same things, and make for a happier, faster, leaner development workflow.

**Comment by balupton** [comment]
Here's what I'm going to do.

- Start a crowd-funding campaign for DocPad v7
- @sdomagala book a time with me in 2 weeks (the week of 27th of Mar) on https://balupton.com and we'll get this sorted, in fact, we can spend that week pairing for its entirety if you want

**Comment by sdomagala** [comment]
> @sdomagala book a time with me in 2 weeks (the week of 27th of Mar) on https://balupton.com and we'll get this sorted, in fact, we can spend that week pairing for its entirety if you want

Will do!

> I wish DocPad the best, and I hope it is able to regain traction and fulfill the promise of its destiny. But until there are signs of that happening, then maybe the best solution for you is to find an alternative to DocPad. I personally love Metalsmith. DocPad’s own @RobLoach has made some contributions to the project (especially in terms of JSTransformer plugins). It’s a much more lightweight tool (and performs very fast!), incredibly flexible, and has plugins to replicate all the functionality that I loved about DocPad.

We rely to heavily on DocPad to switch it - we have number of customized plugins for our needs, but some of the work you simply want to give back to the community :)

**Comment by balupton** [comment]
@sdomagala fixed the meeting url

**Comment by balupton** [comment]
for crowd fund - http://www.codefund.io/view.php?id=4 over at https://github.com/docpad/docpad/issues/1055

**Comment by balupton** [comment]
added in the now released v2.5.0

**Comment by sdomagala** [comment]
Thanks for help on this PR!

**Pull request closed without merging**
